var searchData=
[
  ['c3dmap',['C3DMap',['../class_c3_d_map.html',1,'']]],
  ['caisocket',['CAISocket',['../class_c_a_i_socket.html',1,'']]],
  ['canattack',['CanAttack',['../struct_c_npc.html#a557f3d626834d1eb31b6954c0b657703',1,'CNpc::CanAttack()'],['../class_unit.html#a07ad7e76f96c9c8f41d42cc2789f4f1e',1,'Unit::CanAttack()'],['../struct_c_user.html#a6e2c6b203c6318488dcc825ba98ad883',1,'CUser::CanAttack()'],['../struct_c_npc.html#a021faf4591899f10bc82dda985a1cf47',1,'CNpc::CanAttack()']]],
  ['candidacynoticeboard',['CandidacyNoticeBoard',['../class_c_king_system.html#aa5ac433222cd009cd8ca35f30fa2a0b4',1,'CKingSystem']]],
  ['candidacyrecommend',['CandidacyRecommend',['../class_c_king_system.html#a98b99d228c6897a21c1e792506a13fb0',1,'CKingSystem']]],
  ['candidacyresign',['CandidacyResign',['../class_c_king_system.html#a66924b8489c245c82bbe232499f6b5a7',1,'CKingSystem']]],
  ['canuseitem',['CanUseItem',['../struct_c_user.html#acb67910f91e6604b7407741b735d3ca5',1,'CUser']]],
  ['cbattleset',['CBattleSet',['../class_c_battle_set.html',1,'']]],
  ['ccoefficientset',['CCoefficientSet',['../class_c_coefficient_set.html',1,'']]],
  ['cdbagent',['CDBAgent',['../class_c_d_b_agent.html',1,'']]],
  ['cdbprocess',['CDBProcess',['../class_c_d_b_process.html',1,'']]],
  ['ceventset',['CEventSet',['../class_c_event_set.html',1,'']]],
  ['cgameevent',['CGameEvent',['../class_c_game_event.html',1,'']]],
  ['cgamesocket',['CGameSocket',['../class_c_game_socket.html',1,'']]],
  ['changefame',['ChangeFame',['../struct_c_user.html#a9377213532e236e8e40bc3c858dd66b7',1,'CUser']]],
  ['changenp',['ChangeNP',['../struct_c_user.html#ac8a6d40ac9ce73b3c6955c7bbe3feba0',1,'CUser']]],
  ['charactersealprocess',['CharacterSealProcess',['../struct_c_user.html#acb17b0ecc50cec93077bced38e6fcac0',1,'CUser']]],
  ['chatpacket',['ChatPacket',['../class_chat_packet.html',1,'']]],
  ['checkalliance',['CheckAlliance',['../class_c_knights_manager.html#a21ec0cf85c45f2fc9a819e64d43744b6',1,'CKnightsManager']]],
  ['checkexchange',['CheckExchange',['../struct_c_user.html#a5787df0941c731219242064583df1728',1,'CUser']]],
  ['checkkingtimer',['CheckKingTimer',['../class_c_king_system.html#a65755ea73605e49c330c4423964c5c20',1,'CKingSystem']]],
  ['checksavedmagic',['CheckSavedMagic',['../struct_c_user.html#a7f549f2d20ee1007ed5ab1206abd8316',1,'CUser']]],
  ['checkspecialevent',['CheckSpecialEvent',['../class_c_king_system.html#abe25bd8c70989db28455989a65edec98',1,'CKingSystem']]],
  ['checktype3prerequisites',['CheckType3Prerequisites',['../class_magic_instance.html#a9632ae2eed4eaf4139e84da36a94c892',1,'MagicInstance']]],
  ['checktype4prerequisites',['CheckType4Prerequisites',['../class_magic_instance.html#a3f2c37061c9c5f2780d92fb7a5bfc5e8',1,'MagicInstance']]],
  ['chomeset',['CHomeSet',['../class_c_home_set.html',1,'']]],
  ['ci_5fcompare',['ci_compare',['../structci__compare.html',1,'']]],
  ['cini',['CIni',['../class_c_ini.html',1,'']]],
  ['circularbuffer',['CircularBuffer',['../class_circular_buffer.html',1,'CircularBuffer'],['../class_circular_buffer.html#a8c5de0e610bb50bac684f4707e23431c',1,'CircularBuffer::CircularBuffer()']]],
  ['citemexchangeset',['CItemExchangeSet',['../class_c_item_exchange_set.html',1,'']]],
  ['citemopset',['CItemOpSet',['../class_c_item_op_set.html',1,'']]],
  ['citemtableset',['CItemTableSet',['../class_c_item_table_set.html',1,'']]],
  ['citemupgradeset',['CItemUpgradeSet',['../class_c_item_upgrade_set.html',1,'']]],
  ['cjvcryption',['CJvCryption',['../class_c_jv_cryption.html',1,'']]],
  ['ckingcandidacynoticeboardset',['CKingCandidacyNoticeBoardSet',['../class_c_king_candidacy_notice_board_set.html',1,'']]],
  ['ckingelectionlistset',['CKingElectionListSet',['../class_c_king_election_list_set.html',1,'']]],
  ['ckingsystem',['CKingSystem',['../class_c_king_system.html',1,'']]],
  ['ckingsystemset',['CKingSystemSet',['../class_c_king_system_set.html',1,'']]],
  ['cknights',['CKnights',['../class_c_knights.html',1,'']]],
  ['cknightsallianceset',['CKnightsAllianceSet',['../class_c_knights_alliance_set.html',1,'']]],
  ['cknightscapeset',['CKnightsCapeSet',['../class_c_knights_cape_set.html',1,'']]],
  ['cknightsmanager',['CKnightsManager',['../class_c_knights_manager.html',1,'']]],
  ['cknightsrankset',['CKnightsRankSet',['../class_c_knights_rank_set.html',1,'']]],
  ['cknightsset',['CKnightsSet',['../class_c_knights_set.html',1,'']]],
  ['cknightsuserset',['CKnightsUserSet',['../class_c_knights_user_set.html',1,'']]],
  ['cleveluptableset',['CLevelUpTableSet',['../class_c_level_up_table_set.html',1,'']]],
  ['clientsocketmgr',['ClientSocketMgr',['../class_client_socket_mgr.html',1,'']]],
  ['cluaengine',['CLuaEngine',['../class_c_lua_engine.html',1,'']]],
  ['cluascript',['CLuaScript',['../class_c_lua_script.html',1,'']]],
  ['cmagicprocess',['CMagicProcess',['../class_c_magic_process.html',1,'']]],
  ['cmagictableset',['CMagicTableSet',['../class_c_magic_table_set.html',1,'']]],
  ['cmagictype1set',['CMagicType1Set',['../class_c_magic_type1_set.html',1,'']]],
  ['cmagictype2set',['CMagicType2Set',['../class_c_magic_type2_set.html',1,'']]],
  ['cmagictype3set',['CMagicType3Set',['../class_c_magic_type3_set.html',1,'']]],
  ['cmagictype4set',['CMagicType4Set',['../class_c_magic_type4_set.html',1,'']]],
  ['cmagictype5set',['CMagicType5Set',['../class_c_magic_type5_set.html',1,'']]],
  ['cmagictype6set',['CMagicType6Set',['../class_c_magic_type6_set.html',1,'']]],
  ['cmagictype7set',['CMagicType7Set',['../class_c_magic_type7_set.html',1,'']]],
  ['cmagictype8set',['CMagicType8Set',['../class_c_magic_type8_set.html',1,'']]],
  ['cmagictype9set',['CMagicType9Set',['../class_c_magic_type9_set.html',1,'']]],
  ['cmakedefensivetableset',['CMakeDefensiveTableSet',['../class_c_make_defensive_table_set.html',1,'']]],
  ['cmakegradeitemtableset',['CMakeGradeItemTableSet',['../class_c_make_grade_item_table_set.html',1,'']]],
  ['cmakeitemgroupset',['CMakeItemGroupSet',['../class_c_make_item_group_set.html',1,'']]],
  ['cmakelareitemtableset',['CMakeLareItemTableSet',['../class_c_make_lare_item_table_set.html',1,'']]],
  ['cmakeweapontableset',['CMakeWeaponTableSet',['../class_c_make_weapon_table_set.html',1,'']]],
  ['cmontableset',['CMonTableSet',['../class_c_mon_table_set.html',1,'']]],
  ['cnpc',['CNpc',['../struct_c_npc.html',1,'']]],
  ['cnpcitemset',['CNpcItemSet',['../class_c_npc_item_set.html',1,'']]],
  ['cnpcmagicprocess',['CNpcMagicProcess',['../class_c_npc_magic_process.html',1,'']]],
  ['cnpcposset',['CNpcPosSet',['../class_c_npc_pos_set.html',1,'']]],
  ['cnpctable',['CNpcTable',['../class_c_npc_table.html',1,'']]],
  ['cnpctableset',['CNpcTableSet',['../class_c_npc_table_set.html',1,'']]],
  ['cnpcthread',['CNpcThread',['../class_c_npc_thread.html',1,'']]],
  ['command',['Command',['../class_command.html',1,'']]],
  ['compilescript',['CompileScript',['../class_c_lua_script.html#afe966fa00206752390111ecc116bfa90',1,'CLuaScript']]],
  ['condition',['Condition',['../class_condition.html',1,'']]],
  ['cparty',['CParty',['../class_c_party.html',1,'']]],
  ['cpathfind',['CPathFind',['../class_c_path_find.html',1,'']]],
  ['cpoint',['CPoint',['../struct_c_point.html',1,'']]],
  ['cquesthelperset',['CQuestHelperSet',['../class_c_quest_helper_set.html',1,'']]],
  ['cquestmonsterset',['CQuestMonsterSet',['../class_c_quest_monster_set.html',1,'']]],
  ['crect',['CRect',['../class_c_rect.html',1,'']]],
  ['cregion',['CRegion',['../class_c_region.html',1,'']]],
  ['crentalitemset',['CRentalItemSet',['../class_c_rental_item_set.html',1,'']]],
  ['croomevent',['CRoomEvent',['../class_c_room_event.html',1,'']]],
  ['cs',['cs',['../class_mutex.html#aa2061477772bb6d61d341f8b8b1ebf36',1,'Mutex']]],
  ['cserverdlg',['CServerDlg',['../class_c_server_dlg.html',1,'']]],
  ['cserverresourceset',['CServerResourceSet',['../class_c_server_resource_set.html',1,'']]],
  ['csetitemtableset',['CSetItemTableSet',['../class_c_set_item_table_set.html',1,'']]],
  ['csize',['CSize',['../struct_c_size.html',1,'']]],
  ['cstartpositionset',['CStartPositionSet',['../class_c_start_position_set.html',1,'']]],
  ['cstlmap',['CSTLMap',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fk_5fmonster_5fitem_20_3e',['CSTLMap&lt; _K_MONSTER_ITEM &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5floot_5fbundle_20_3e',['CSTLMap&lt; _LOOT_BUNDLE &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fmagic_5ftable_20_3e',['CSTLMap&lt; _MAGIC_TABLE &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fmagic_5ftype1_20_3e',['CSTLMap&lt; _MAGIC_TYPE1 &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fmagic_5ftype2_20_3e',['CSTLMap&lt; _MAGIC_TYPE2 &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fmake_5fitem_5fgrade_5fcode_20_3e',['CSTLMap&lt; _MAKE_ITEM_GRADE_CODE &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fmake_5fitem_5fgroup_20_3e',['CSTLMap&lt; _MAKE_ITEM_GROUP &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fmake_5fitem_5flare_5fcode_20_3e',['CSTLMap&lt; _MAKE_ITEM_LARE_CODE &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fmake_5fweapon_20_3e',['CSTLMap&lt; _MAKE_WEAPON &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fobject_5fevent_20_3e',['CSTLMap&lt; _OBJECT_EVENT &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fparty_5fgroup_20_3e',['CSTLMap&lt; _PARTY_GROUP &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fregene_5fevent_20_3e',['CSTLMap&lt; _REGENE_EVENT &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fserver_5fresource_20_3e',['CSTLMap&lt; _SERVER_RESOURCE &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20_5fwarp_5finfo_20_3e',['CSTLMap&lt; _WARP_INFO &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20c3dmap_20_3e',['CSTLMap&lt; C3DMap &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20cgameevent_20_3e',['CSTLMap&lt; CGameEvent &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20cnpc_20_3e',['CSTLMap&lt; CNpc &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20cnpctable_20_3e',['CSTLMap&lt; CNpcTable &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20croomevent_20_3e',['CSTLMap&lt; CRoomEvent &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cstlmap_3c_20int_20_3e',['CSTLMap&lt; int &gt;',['../class_c_s_t_l_map.html',1,'']]],
  ['cuser',['CUser',['../struct_c_user.html',1,'']]],
  ['cuserknightsrankset',['CUserKnightsRankSet',['../class_c_user_knights_rank_set.html',1,'']]],
  ['cuserpersonalrankset',['CUserPersonalRankSet',['../class_c_user_personal_rank_set.html',1,'']]],
  ['czoneinfoset',['CZoneInfoSet',['../class_c_zone_info_set.html',1,'']]]
];
